name: 'hashdown'
version: 1.0.2
description: >
  Hashdown is an  file/text-to-text encoding scheme designed for safe and compact data sharing
homepage: http://www.hashdown.net
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  base2e15: any
  crypto: any
  lzma: any
dev_dependencies:
  test: any
