name: 'hashdown'
version: 1.0.1
description: >
  An absolute bare-bones web app.
homepage: http://www.hashdown.net
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  base2e15: any
  crypto: any
  lzma: any
